server:
  port: 8083
spring:
  application:
    name: data-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/energy_station?serverTimezone=UTC
    username: root
    password: admin
  cloud:
    nacos:
      discovery:
        server-addr: 101.35.83.193:8848
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

