server:
  port: 8888
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USERSERVICE
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: data-service
          uri: lb://DATASERVICE
          predicates:
            - Path=/data/**
          filters:
            - StripPrefix=1
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka
logging:
  level:
    org.springframework.cloud.gateway: debug
