server:
  port: 8888
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: data-service
          uri: lb://data-service
          predicates:
            - Path=/data/**
          filters:
            - StripPrefix=1
        - id: system-status-service
          uri: lb://system-status-service
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    nacos:
      discovery:
        server-addr: 101.35.83.193:8848
logging:
  level:
    org.springframework.cloud.gateway: debug
