server:
  port: 8084
spring:
  application:
    name: system-status-service
  cloud:
    nacos:
      discovery:
        server-addr: 101.35.83.193:8848
      config:
        server-addr: 101.35.83.193.8848